tomcatserver:
    image: tomcat
    container_name: tomcat
    ports:
        - 8080
    hostname: tomcat
    links:
        - mongodb:mongo
            
mongodb:
    image: mongo
    container_name: mongo
    ports:
        - 27017
    hostname: mongo
    volumes:
        - $HOME/mongo/data/db:/data/db
        
